# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TPvIoABgavh-UAYhVD4imHsQB_RbghYE
"""

postfix_expression = input("Enter the postfix expression: ")

stack = []

for char in postfix_expression:
    if char.isdigit():
        stack.append(int(char))
    else:
        operand2 = stack.pop()
        operand1 = stack.pop()
        if char == '+':
            stack.append(operand1 + operand2)
        elif char == '-':
            stack.append(operand1 - operand2)
        elif char == '*':
            stack.append(operand1 * operand2)
        elif char == '/':
            stack.append(operand1 / operand2)

result = stack[0]
print("Result:", result)