# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ng7QIYHIScUGRNXbR6i6guR5jvJ2J24z
"""

s = input("Enter a string: ")
count = 0
n = len(s)

# Iterate through each character in the string
for i in range(n):
   lower = 0
   upper = 0

   # Check for substrings starting from the current character
   for j in range(i, n):
       if s[j].islower():
           lower += 1
       else:
           upper += 1

       # If the number of lowercase and uppercase letters is equal, increment the count
       if lower == upper:
           count += 1

print(count)

s = input("Enter a string: ")
count = 0
n = len(s)

# Iterate through each character in the string
for i in range(n):
   lower = 0
   upper = 0

   # Check for substrings starting from the current character
   for j in range(i, n):
       if s[j].islower():
           lower += 1
       else:
           upper += 1

       # If the number of lowercase and uppercase letters is equal, increment the count
       if lower == upper:
           count += 1

print(count)