# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C9A23wcdxuv0K0MSIEIoghZisV1Sb8cC
"""

def max_chess_games(hours):
   minutes = hours * 60  # Convert hours to minutes
   games = minutes // 20  # Calculate the maximum number of complete games
   return games

user_input = int(input("Enter the number of hours of free time: "))

result = max_chess_games(user_input)
print("The maximum number of complete chess games Chef can play is:", result)

def max_chess_games(hours):
   minutes = hours * 60  # Convert hours to minutes
   games = minutes // 20  # Calculate the maximum number of complete games
   return games

user_input = int(input("Enter the number of hours of free time: "))

result = max_chess_games(user_input)
print("The maximum number of complete chess games Chef can play is:", result)

def max_chess_games(hours):
   minutes = hours * 60  # Convert hours to minutes
   games = minutes // 20  # Calculate the maximum number of complete games
   return games

user_input = int(input("Enter the number of hours of free time: "))

result = max_chess_games(user_input)
print("The maximum number of complete chess games Chef can play is:", result)