# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RgCmfyd_VweHReTIw8HeaIoZ7zNMg7cP
"""

friends = int(input("Enter the number of friends: "))
cost_per_burger = int(input("Enter the cost of each burger: "))
total_money = int(input("Enter the total amount of money Chef has: "))

total_cost = friends * cost_per_burger


if total_cost <= total_money:
   print("Yes, Chef can buy burgers for all his friends.")
else:
   print("No, Chef cannot buy burgers for all his friends.")

friends = int(input("Enter the number of friends: "))
cost_per_burger = int(input("Enter the cost of each burger: "))
total_money = int(input("Enter the total amount of money Chef has: "))

total_cost = friends * cost_per_burger


if total_cost <= total_money:
   print("Yes, Chef can buy burgers for all his friends.")
else:
   print("No, Chef cannot buy burgers for all his friends.")

friends = int(input("Enter the number of friends: "))
cost_per_burger = int(input("Enter the cost of each burger: "))
total_money = int(input("Enter the total amount of money Chef has: "))

total_cost = friends * cost_per_burger


if total_cost <= total_money:
   print("Yes, Chef can buy burgers for all his friends.")
else:
   print("No, Chef cannot buy burgers for all his friends.")