# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xz6h4kcV6hbugaAjMo_WbmFJJVM0DTAc
"""

import math

def check_username(username):
   if len(username) % 2 == 1:
       print( "The user is a boy")
   else:
       print("The user is a girl")

# Get user input for the username
username = input("Enter the username: ")

result = check_username(username)
print(result)

def check_username(username):
   if len(username) % 2 == 1:
       print( "The user is a boy")
   else:
       print("The user is a girl")

# Get user input for the username
username = input("Enter the username: ")

result = check_username(username)
print(result)