# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iSvJW5kfj-_k4l-ikrDnG27l6mPneXO0
"""

n = int(input("Enter the number of elements in the array: "))
Arr = []
for i in range(n):
   num = int(input("Enter element " + str(i+1) + ": "))
   Arr.append(num)

positive = [num for num in Arr if num > 0]
negative = [num for num in Arr if num < 0]

#To Check
result = []
if len(positive) >= len(negative):
   for i in range(len(negative)):
       result.append(positive[i])
       result.append(negative[i])
   result += positive[len(negative):]
else:
   for i in range(len(positive)):
       result.append(negative[i])
       result.append(positive[i])
   result += negative[len(positive):]

print("Alternate positive and negative numbers array:", result)