# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dM7qYo_hlkrJB5ubSvnCual52uBa8RaQ
"""

# Take input for the set of integers
nums = list(map(int, input("INPUT : ").split()))

distinct_sums = set()

def generate_sums(index, current_sum):
    if index == len(nums):
        distinct_sums.add(current_sum)
        return
    generate_sums(index + 1, current_sum + nums[index])
    generate_sums(index + 1, current_sum)

generate_sums(0, 0)


print("OUTPUT :", sorted(list(distinct_sums)))