# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i4K_20Z1G3nk-jRr8ibJkN5niuQzxhLJ
"""

array = list(map(int, input("Please enter the array of numbers").split()))

target = int(input("Please enter the target number: "))

result = find_sum_of_two(array, target)

if result:
   print(f"The pair of numbers that sum up to {target} is: {result[0]} and {result[1]}")
else:
   print("No pair of numbers found that sum up to the target.")

array = list(map(int, input("Please enter the array of numbers").split()))

target = int(input("Please enter the target number: "))

result = find_sum_of_two(array, target)

if result:
   print(f"The pair of numbers that sum up to {target} is: {result[0]} and {result[1]}")
else:
   print("No pair of numbers found that sum up to the target.")