# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wDbdbjxmYNjE6sF5e4U_S8EJsAst7nsK
"""

S = input("Enter a string: ")
char_freq = {}
for char in S:
    char_freq[char] = char_freq.get(char, 0) + 1
non_repeating_char = 'f'
for char in S:
    if char_freq[char] == 1:
        non_repeating_char = char
        break

print("output", non_repeating_char)

S = input("Enter a string: ")
char_freq = {}
for char in S:
    char_freq[char] = char_freq.get(char, 0) + 1
non_repeating_char = 'f'
for char in S:
    if char_freq[char] == 1:
        non_repeating_char = char
        break

print("output", non_repeating_char)